FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY weather_station.py .
COPY --from=iot-farm-broker:latest /tmp/ca.crt /app/ca.crt

ENV BROKER_HOST=broker
ENV BROKER_PORT=8883
ENV DEVICE_ID=gippsland-weather-01

CMD [ "python3", "weather_station.py" ]