services:
  broker:
    build: ./mqtt-broker
    ports:
      - "1883:1883"
    networks:
      - farm-net

  device:
    build:
      context: .
      dockerfile: Dockerfile.device
    container_name: iot-device
    depends_on:
      - broker
    networks:
      - farm-net
    environment:
      - DEVICE_ID=paddock-sensor-01
      - BROKER_HOST=broker
      - BROKER_PORT=8883
  
  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    container_name: iot-subscriber
    depends_on:
      - broker
    networks:
      - farm-net
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=8883

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: iot-monitor
    depends_on:
      - subscriber
    networks:
      - farm-net
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=8883
  
networks:
  farm-net:
    driver: bridge